export const HttpConstants = {
   HTTP_HEADER_ACCEPT : 'Accept',
   HTTP_HEADER_AUTHORIZATION : 'Authorization',
   HTTP_HEADER_CONTENT_TYPE : 'Content-Type',
   HTTP_HEADER_TENANTID : 'X-Tenant-id',

   HTTP_HEADER_VALUE_APPLICATIONJSON : 'application/json',
   HTTP_HEADER_VALUE_BASIC_PREFIX : 'Basic',
   HTTP_HEADER_VALUE_BEARER_PREFIX : 'Bearer',

   HTTP_METHOD_GET : 'GET',
   HTTP_METHOD_DELETE : 'DELETE',
   HTTP_METHOD_PATCH : 'PATCH',
   HTTP_METHOD_POST : 'POST',
   HTTP_METHOD_PUT : 'PUT',

   HTTP_STATUSCODE_OK : 200,
   HTTP_STATUSCODE_CREATED : 201,
   HTTP_STATUSCODE_ACCEPTED : 202,
   HTTP_STATUSCODE_UNAUTHORIZED : 401,
   HTTP_STATUSCODE_FORBIDDEN : 403,
   HTTP_STATUSCODE_NOTFOUND : 404,
   HTTP_STATUSCODE_INTERNAL_SERVER_ERROR : 500,
   HTTP_STATUSCODE_SERVICE_UNAVAILBLE : 503
};
