export const JwtConstants = {
   JWT_REFRESH_URL_PARAM : 'refresh_token',
   JWT_STORE_ACCESSTOKEN_KEY : 'jwt_access_token',
   JWT_STORE_REFRESHTOKEN_KEY : 'jwt_refresh_token',

   JWT_TOKEN_PROPERTY_AUT : 'authorities',
   JWT_TOKEN_PROPERTY_EXP : 'exp',
   JWT_TOKEN_PROPERTY_TID : 'tid',
   JWT_TOKEN_PROPERTY_USERNAME : 'user_name',
   JWT_TOKEN_PROPERTY_UID : 'uid',

   JWT_REFRESH_CHECK_INTERVAL_IN_SECONDS: 40,
   JWT_REFRESH_CHECK_POLLING_START_BEFORE_EXP_IN_SECONDS: 130
};
